#!/bin/sh
# wclatex-git COMMIT1 COMMIT2
#
# Outputs the word-diff statistics between the two provided commits.
# Can also be used as an GIT_EXTERNAL_DIFF directly (then, accepts all 5 args):
#
# GIT_EXTERNAL_DIFF=wclatex-git git --no-pager  diff COMMIT1 COMMIT2 -- file.tex
#
# Requires pandoc with its sources available since it uses a Haskell filter for
# pandoc.

if [ "$#" -eq 2 ]; then
    DESCRIPTOR=$(basename $1)
    FILE_OLD=$1
    FILE_NEW=$2
else
    DESCRIPTOR=$1
    FILE_OLD=$2
    FILE_NEW=$5
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TMPFILE_OLD=$(mktemp)
TMPFILE_NEW=$(mktemp)
trap "{ rm -f $TMPFILE_OLD $TMPFILE_NEW; }" EXIT

pandoc -t plain --filter $DIR/filtermath.hs $FILE_NEW > $TMPFILE_NEW
if [ $? -ne 0 ]; then
    >&2 echo "Could not parse REMOTE for $DESCRIPTOR"
    exit 0
fi

if [ $FILE_OLD = "/dev/null" ]; then
    WORDS=$(wc -w $TMPFILE_NEW | xargs | awk -F' ' '{print $1}')
    STAT="$WORDS words $WORDS 100% inserted"
else
    pandoc -t plain --filter $DIR/filtermath.hs $FILE_OLD > $TMPFILE_OLD
    if [ $? -ne 0 ]; then
        >&2 echo "Could not parse LOCAL for $DESCRIPTOR"
        exit 0
    fi
    STAT=$(wdiff --statistics $TMPFILE_OLD $TMPFILE_NEW | tail -n1 | awk -F':' '{print $2}' | xargs)
fi

echo "$DESCRIPTOR:$STAT"
